language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  # install composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  # install Neo4j
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

script: phpunit

jdk:
  - oraclejdk7  # needed for local Neo4j 2.0+

env:
  - NEO4J_VERSION="2.0.3"
